cfg_plot = {
    "signal": "ttHTobb",
    "labels": {
        "ttHTobb": "$t\\bar{t}H\\rightarrow b\\bar{b}$",
        "TTToSemiLeptonic": "$t\\bar{t}$ semilep.",
        "TTTo2L2Nu" : "$t\\bar{t}$ dilepton",
        "SingleTop" : "Single t",
        "WJetsToLNu_HT" : "W+jets",
    },
    "variables": {
        "JetGood_pt_1": {'xlim' : (0,500), 'xlabel' : "$p_{T}^{j,1}$ [GeV]"},
        "JetGood_pt_2": {'xlim' : (0,500), 'xlabel' : "$p_{T}^{j,2}$ [GeV]"},
        "JetGood_pt_3": {'xlim' : (0,500), 'xlabel' : "$p_{T}^{j,3}$ [GeV]"},
        "JetGood_pt_4": {'xlim' : (0,500), 'xlabel' : "$p_{T}^{j,4}$ [GeV]"},
        "JetGood_pt_5": {'xlim' : (0,500), 'xlabel' : "$p_{T}^{j,5}$ [GeV]"},
        "JetGood_pt_6": {'xlim' : (0,500), 'xlabel' : "$p_{T}^{j,6}$ [GeV]"},
        "JetGood_eta_1": {'xlabel' : "$\eta_{j,1}$"},
        "JetGood_eta_2": {'xlabel' : "$\eta_{j,2}$"},
        "JetGood_eta_3": {'xlabel' : "$\eta_{j,3}$"},
        "JetGood_eta_4": {'xlabel' : "$\eta_{j,4}$"},
        "JetGood_eta_5": {'xlabel' : "$\eta_{j,5}$"},
        "JetGood_eta_6": {'xlabel' : "$\eta_{j,6}$"},
        "JetGood_phi_1": {'xlabel' : "$\phi_{j,1}$"},
        "JetGood_phi_2": {'xlabel' : "$\phi_{j,2}$"},
        "JetGood_phi_3": {'xlabel' : "$\phi_{j,3}$"},
        "JetGood_phi_4": {'xlabel' : "$\phi_{j,4}$"},
        "JetGood_phi_5": {'xlabel' : "$\phi_{j,5}$"},
        "JetGood_phi_6": {'xlabel' : "$\phi_{j,6}$"},
        "JetGood_btagDeepFlavB_1": {'xlabel' : "AK4 DeepJet b-tag score (Jet 1)"},
        "JetGood_btagDeepFlavB_2": {'xlabel' : "AK4 DeepJet b-tag score (Jet 2)"},
        "JetGood_btagDeepFlavB_3": {'xlabel' : "AK4 DeepJet b-tag score (Jet 3)"},
        "JetGood_btagDeepFlavB_4": {'xlabel' : "AK4 DeepJet b-tag score (Jet 4)"},
        "JetGood_btagDeepFlavB_5": {'xlabel' : "AK4 DeepJet b-tag score (Jet 5)"},
        "JetGood_btagDeepFlavB_6": {'xlabel' : "AK4 DeepJet b-tag score (Jet 6)"},
        "nBJets": {'xlim' : (1,8), 'scale' : "log"},
        "nJets": {'xlim' : (4,14), 'scale' : "log"},
    }
}
