# This config has been generated by the pocket_coffea CLI 0.9.4.
import os

from custom_cut_functions import *
from workflow_datacard_creation import BasicProcessor

from pocket_coffea.lib.calibrators.common import default_calibrators_sequence
from pocket_coffea.lib.columns_manager import ColOut
from pocket_coffea.lib.cut_functions import eventFlags, get_HLTsel, get_nObj_min, get_nPVgood, goldenJson
from pocket_coffea.parameters.cuts import passthrough
from pocket_coffea.parameters.histograms import *
from pocket_coffea.utils.configurator import Configurator

localdir = os.path.dirname(os.path.abspath(__file__))

# Creating weights configuration
from pocket_coffea.lib.weights.common import common_weights

# Loading default parameters
from pocket_coffea.parameters import defaults

default_parameters = defaults.get_default_parameters()
defaults.register_configuration_dir("config_dir", localdir + "/params")

parameters = defaults.merge_parameters_from_files(default_parameters,
                                                    f"{localdir}/params/object_preselection_run3.yaml",
                                                    f"{localdir}/params/triggers.yaml",
                                                    f"{localdir}/params/jets_calibration_noJER.yaml",
                                                   update=True)

# Creating custom weight
cfg = Configurator(
    parameters=parameters,
    datasets={
        "jsons": ['datasets/datasets_cern.json'],
        "filter": {
            "samples": ["DATA_SingleEle", "TTTo2L2Nu", "backgroundSample"],
            "samples_exclude": [],
            "year": ['2022_postEE', '2023_postBPix']
        },
        "subsamples": {}
    },
    workflow=BasicProcessor,

    skim=[get_nPVgood(1), eventFlags, goldenJson,
            get_HLTsel(primaryDatasets=["SingleMuon", "SingleEle"])],

    preselections=[passthrough],
    categories={
        "baseline": [passthrough],
        "1btag": [get_nObj_min(1, coll="BJetGood")],
        "tt2l": [passthrough],
    },

    weights={
        "common": {
            "inclusive": ["genWeight", "lumi", "XS", "pileup",
                          "sf_ele_id", "sf_ele_reco",
                          "sf_mu_id", "sf_mu_iso"
                          ],
            "bycategory": {
                "1btag": ["sf_btag"],
                "tt2l": ["sf_btag"],
            },
        },
        "bysample": {
        }
    },
    # Passing a list of WeightWrapper objects
    weights_classes=common_weights,
    calibrators=default_calibrators_sequence,

    variations={
        "weights": {
            "common": {
                "inclusive": ["pileup",
                               "sf_ele_id", "sf_ele_reco",
                               "sf_mu_id", "sf_mu_iso",
                               ],
                "bycategory": {
                    "1btag": ["sf_btag"],
                    "tt2l": ["sf_btag"],
                }
            },
            "bysample": {
            }
        },
        "shape": {
            "common": {
                "inclusive": ["jet_calibration"],
            },
        }
    },

    variables={
        "MET_pt": HistConf([Axis(coll="MET", field="pt", label="MET pT [GeV]", bins=50, start=0, stop=200)]),
    },

    columns={
        "common": {
            "inclusive": [
                ColOut(collection="Jet", columns=["pt"]),
                ColOut(collection="PuppiMET", columns=["pt", "phi"]),
                ColOut(collection="Electron", columns=["pt", "eta"]),
            ]

        }
    },
)
