# This code has been generated by the pocket_coffea CLI 0.9.4.
import awkward as ak
from pocket_coffea.lib.cut_definition import Cut

def cut_function(events, params, year, sample, **kwargs):
    # Put here your selection logic
    return ak.ones_like(events.event, dtype=bool)

cut = Cut(
    name="cut_name",
    params={
        "param1": 1,
        "param2": 2,
    },
    function=cut_function,
)
